[package]
name = "tinyrlibc"
version = "0.4.0"
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
edition = "2021"
description = "Tiny, incomplete C library for bare-metal targets, written in Stable (but Unsafe) Rust"
license-file = "LICENCES.md"
readme = "README.md"
repository = "https://github.com/rust-embedded-community/tinyrlibc"

[dependencies]
portable-atomic = { version = "1.6.0", optional = true }

[dev-dependencies]
static-alloc = "0.2.4"

[build-dependencies]
cc = "1.0"

[features]
default = ["all"]
all = [
    "abs",
    "strcmp",
    "strncmp",
    "strncasecmp",
    "strcpy",
    "strcat",
    "strncpy",
    "strlen",
    "strtol",
    "strtoul",
    "strtoll",
    "strtoull",
    "strtoimax",
    "strtoumax",
    "strstr",
    "strchr",
    "strrchr",
    "atoi",
    "utoa",
    "itoa",
    "snprintf",
    "isspace",
    "isdigit",
    "isalpha",
    "isupper",
    "memchr",
    "qsort",
]
abs = []
strcmp = []
strncmp = []
strncasecmp = []
strcpy = []
strcat = []
strncpy = []
strlen = []
strtol = []
strtoul = []
strtoll = []
strtoull = []
strtoimax = []
strtoumax = []
strstr = []
strchr = []
strrchr = []
atoi = []
utoa = []
itoa = []
snprintf = []
isspace = []
isdigit = []
isalpha = []
isupper = []
alloc = []
memchr = []
qsort = []
signal = ["dep:portable-atomic"]
signal-cs = ["portable-atomic/critical-section"]
